runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  DB_CONNECTION: mysql
  DB_DATABASE: sekarsari-laravel
  APP_NAME: Sekarsari
  DB_HOST: projects/iqbalpamula/secrets/db_host/versions/latest:access
  DB_PORT: projects/iqbalpamula/secrets/db_port/versions/latest:access
  DB_USERNAME: projects/iqbalpamula/secrets/db_username/versions/latest:access
  DB_PASSWORD: projects/iqbalpamula/secrets/db_password/versions/latest:access
  APP_KEY: projects/iqbalpamula/secrets/laravel_app_key/versions/latest:access

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Copy composer.lock and composer.json to the container
# and set the working directory
copy_files:
  - source: composer.lock
    destination: /app
  - source: composer.json
    destination: /app
  - source: ./
    destination: /app

# Install dependencies using Composer
install: true

# Set the entrypoint command to run migration.sh
entrypoint: /app/migration.sh
