runtime: php
services: default
env: flex

runtime_config:
  document_root: public

env_variables:
  DB_CONNECTION: mysql
  DB_DATABASE: sekarsari-laravel
  APP_NAME: Sekarsari

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Use the official PHP 8.1 image as the base image
image: gcr.io/google-appengine/php81

# Copy composer.lock and composer.json to the container
# and set the working directory
copy_files:
  - source: composer.lock
    destination: /app
  - source: composer.json
    destination: /app
  - source: ./
    destination: /app

# Install dependencies using Composer
install: true

# Set the entrypoint command to run migration.sh
entrypoint: /app/migration.sh
