steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sekarsari-laravel:$COMMIT_SHA'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sekarsari-laravel:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sekarsari-laravel'
      - '--image=gcr.io/$PROJECT_ID/sekarsari-laravel:$COMMIT_SHA'
      - '--region=us-central1'
      - '--cpu=2'
      - '--memory=2048Mi'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/sekarsari-laravel:$COMMIT_SHA'
logsBucket: 'gs://sekarsari-laravel-bucket/logs'